### ISSUE TITLE
目录删除

### ISSUE THREAD

**Issue by lengyijun** [ResearchHelper/research-helper#26]
我第一次打开的时候,直接选中了我保存论文的目录
后来又在设置中,改成了一个新目录
然后我发现本来的目录不见了
里面的paper也没有了

**Comment by HuntFeng** [comment]
天啊，这个问题我确实没有考虑周全。在设置中改变储存路径的时候，旧路径下的文件会全部转移到新路径下。你去新路径下面找找吧。以后我会添加一个判断，只会转移这款软件相关的那些文件。

**Comment by lengyijun** [comment]
Ok , I find it
