### ISSUE TITLE
无法执行'yarn build'命令

### ISSUE THREAD

**Issue by Jack251970** [ResearchHelper/research-helper#32]
![image](https://user-images.githubusercontent.com/53996452/236841408-04768dfd-9d47-40b0-bad2-8232b67c9521.png)
在package.json中也不存在build命令？

**Comment by HuntFeng** [comment]
这是因为我是用[action-electron-builder](https://github.com/ResearchHelper/action-electron-builder)来自动build的。它在用electron-builder去build之前还会跑一次package.json里面的build命令。我懒，直接就删掉build那行东西了。我这几天就会进行下一次的更新，我会把build这部分东西也完善好。

你现在可以先使用`yarn run quasar build -m electron`来build。

**Comment by HuntFeng** [comment]
build script has been added in `v2.0.0-beta` release
