### ISSUE TITLE
很棒很棒，提几个建议

### ISSUE THREAD

**Issue by shydyl** [ResearchHelper/research-helper#39]
1. 文章的详细信息可以增加文章所在的分组
2. 将文章添加到左面的分组时，希望可以多选，不然一个一个拖动有些慢
3. 如果能加入文献翻译功能（类似知云），就更好了（可能有点困难昂）

希望软件可以越做越好，加油

**Comment by HuntFeng** [comment]
感谢支持！第一个建议很不错！后面两个都在计划当中，在肝了！哈哈。
