### ISSUE TITLE
Button theme mismatching interface issue

### ISSUE THREAD

**Issue by Jack251970** [ResearchHelper/research-helper#46]
There seems to exist different interface style between 'zoom in' button and 'zoom out' button, and between 'enter full screen' button and 'exit full screen button.

![image](https://github.com/ResearchHelper/research-helper/assets/53996452/8ecfb845-326f-4fbd-8215-c56c2f67cde6)

![image](https://github.com/ResearchHelper/research-helper/assets/53996452/74b0458d-d1c6-481b-8981-eeaaa8b5c935)
![image](https://github.com/ResearchHelper/research-helper/assets/53996452/a4a2e1c4-838c-4ebb-863a-9e7dd4df0b63)

**Comment by HuntFeng** [comment]
Lol 😂 must be the dark theme so I didn't notice that. 

This only requires a small fix. If you like, you could fix that in your pull request, I will review them altogether. 

Thank you so much for spotting this 😆

**Comment by Jack251970** [comment]
I'm curious why these noticeable bugs exist at even 2.0.1-beta version without fixing and It turned out to be a problem of the theme. 😂

**Comment by HuntFeng** [comment]
Because the dark theme is dark enough so I can't notice the difference. 😂
