### ISSUE TITLE
改进的建议

### ISSUE THREAD

**Issue by MaoSong2022** [ResearchHelper/research-helper#48]
我在ubuntu20.04上试用了2.0.1-beta版本，确实很好用，特别是pdf阅读功能很强大。但是，在试用的过程中我遇到了以下问题
1. (bug) create entry by file时，有时候会显示出错，但是文件还是被添加了
2. (feature) 希望能够增加更多fields用来排序文件，比如zotero就提供了publication， date added等fields
3. (bug) 从pdf阅读界面切换到library界面的时候，library界面的排序功能，详情功能都无了
4. (bug) 每次点开详情界面，都需要重新点击一下文件才能显示文件详情 (即使文件已经高亮显示)
5. (feature) 希望能像zotero一样增加一个显示已有标签的功能，比如我想给一个文件增加一个tag，输入时可以显示已有的tag

希望作者可以继续加油！

**Comment by HuntFeng** [comment]
感谢支持哦！

第一个应该不是bug。加入文件的时候小助手会扫描文档前几页来获取DOI之类的信息，以此来发送请求到doi.org之类的地方获取详细信息。只要其中一步不行，就会有报错。不过文件还是会正常添加，只不过详细信息就缺斤少两而已。后面我会改进一下错误提示的。

其它的都是非常好的建议！
