### ISSUE TITLE
对中文支持好像不好

### ISSUE THREAD

**Issue by Alafun** [ResearchHelper/research-helper#49]
![image](https://github.com/ResearchHelper/research-helper/assets/78416589/678e95a1-46a2-48b8-9756-3142d952e5a2)

好像很容易卡死,不知道是不是非原生的原因

**Comment by HuntFeng** [comment]
🤔按理来说渲染pdf跟是不是中文的应该没啥关系，你可以把pdf上传到github或者什么网盘吗？我去看看。或者你把pdf的网址给我也行。

**Comment by Alafun** [comment]
https://github.com/ResearchHelper/research-helper/issues/50#issuecomment-1559151621

**Comment by Alafun** [comment]
fixed
