### ISSUE TITLE
Windows环境下点击连接好像没有窗口显示

### ISSUE THREAD

**Issue by Alafun** [ResearchHelper/research-helper#50]

**Comment by Alafun** [comment]
文档内部的链接
![动画](https://github.com/ResearchHelper/research-helper/assets/78416589/5b8d5a4a-cf19-48b8-9469-00e79f018ae3)

**Comment by HuntFeng** [comment]
可以上传一下pdf到什么地方吗？我去下载看看怎么回事。

**Comment by Alafun** [comment]
[1cf41677-33eb-445c-b51f-7b73839b7ec4.zip](https://github.com/ResearchHelper/research-helper/files/11543475/1cf41677-33eb-445c-b51f-7b73839b7ec4.zip)
这个是中文显示的问题文件

**Comment by Alafun** [comment]
https://arxiv.org/pdf/1812.04948.pdf

**Comment by Alafun** [comment]
fixed
