### ISSUE TITLE
Enhance建议

### ISSUE THREAD

**Issue by caibimiaokong** [ResearchHelper/research-helper#51]
软件很不错，阅读文献的基本功能都具备了，甚至比zotero好。但还是有几点建议希望作者采纳。
- 有开发者在obsidian笔记软件上开发出类似于research-helper的插件，但体验感不如你这个，但是不同md笔记间引用的引用力度非常细(可以具体到一篇md的一段话并在当前md文件下引用且显示)
- 可以开发出ipad版吗？
- 希望能支持webdav同步
- 兼容zotero的插件

**Comment by HuntFeng** [comment]
感谢你的支持！

- ipad版的在计划中了，但是目前只有我一个在开发。恐怕还得等上一段时间。
- 虽然我不搞webdav，但是云同步功能也在计划中了。哈哈，当然还得等上一段时间。
- 兼容zotero插件这个实在不行，毕竟是两款不同的软件，它们的结构和api都不同。

**Comment by Alafun** [comment]
1. 划词翻译
2. ctrl+w 删除当前标签页
不知道是不是伪需求

**Comment by MachineGUN001** [comment]
打开了四篇pdf文献，内存占用达到了1G，这正常情况吗？

**Comment by HuntFeng** [comment]
> 打开了四篇pdf文献，内存占用达到了1G，这正常情况吗？

听起来有点离谱，我看看怎么回事。

**Comment by MachineGUN001** [comment]
> > 打开了四篇pdf文献，内存占用达到了1G，这正常情况吗？
> 
> 听起来有点离谱，我看看怎么回事。

我下载使用的版本是`Research-Helper-3.0.0-beta-win`，谢谢查看
感谢开发这么好的工具，有点MarginNote +zotero的综合体

性能还是很重要的，要管理好内存使用。期待更好的性能管理

**Comment by HuntFeng** [comment]
> > > 打开了四篇pdf文献，内存占用达到了1G，这正常情况吗？
> > 
> > 
> > 听起来有点离谱，我看看怎么回事。
> 
> 我下载使用的版本是`Research-Helper-3.0.0-beta-win.zip`，谢谢查看 感谢开发这么好的工具，有点MarginNote +zotero的综合体
> 
> 性能还是很重要的，要管理好内存使用。期待更好的性能管理

确认情况了，确实如此。我去学学怎么减少内存使用。
