### ISSUE TITLE
Wanted feature: render basic HTML tag like <img> or <table>

### ISSUE THREAD

**Issue by zhangshaos** [ResearchHelper/research-helper#56]
Embed HTML rendering provides fine-grained control than Markdown.

**Comment by zhangshaos** [comment]
It is okay for `<table>` tag, but it's strange for `<img>` tag.

<img src='https://github.com/ResearchHelper/research-helper/assets/33301662/ece72778-649a-442e-a2be-153c33a5dc06' width='400px' alt='https://github.com/ResearchHelper/research-helper/assets/33301662/ece72778-649a-442e-a2be-153c33a5dc06'/>

<img src='https://github.com/ResearchHelper/research-helper/assets/33301662/aa60e74d-5699-481a-9704-96bc48a01311' width='600px' alt='https://github.com/ResearchHelper/research-helper/assets/33301662/aa60e74d-5699-481a-9704-96bc48a01311'/>

The picture a.jpg is not existed, which should be okay for HTML rendering.

**Comment by zhangshaos** [comment]
> Research Helper supports image and table rendering through markdown syntax.
> 
> Can you tell me more about the use cases of the img and table tags?

It is okay for `<table>` tag, but it's strange for `<img>` tag.

<img src='https://github.com/ResearchHelper/research-helper/assets/33301662/ece72778-649a-442e-a2be-153c33a5dc06' width='400px' alt='https://github.com/ResearchHelper/research-helper/assets/33301662/ece72778-649a-442e-a2be-153c33a5dc06'/>

<img src='https://github.com/ResearchHelper/research-helper/assets/33301662/aa60e74d-5699-481a-9704-96bc48a01311' width='600px' alt='https://github.com/ResearchHelper/research-helper/assets/33301662/aa60e74d-5699-481a-9704-96bc48a01311'/>

The picture a.jpg is not existed, which should be okay for HTML rendering.

**Comment by HuntFeng** [comment]
Simply paste your image into the editor or use the upload button in the toolbar, it will do the rest for you. 

As for the table. Create it using markdown syntax or the button in the toolbar. To increase/delete row/column, refer to shortcuts listed in help.
