### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by jasonzou** [ResearchHelper/research-helper#57]
Thanks for making this available! I would like to see the following features that could improve the usefulness of this software.

1. Meta info - journal title, conference, publisher, editor are missing. Zotero is more completed.
2. Bibliography generation which requires more metadata information.
3. The current list of items window has two columns (title and author). More columns are better. If columns could be customized, that will be great.

By the way, I am studying your code and will contribute to this project later.

Thanks

**Comment by HuntFeng** [comment]
> Meta info - journal title, conference, publisher, editor are missing. Zotero is more completed.

I am working on this now. You will see improvement in the next release. 

> Bibliography generation which requires more metadata information.

In fact, this app store meta info including publisher, journal title and more in the database (I just didn't show them in meta info tab). Could you tell me which information is missing?

> The current list of items window has two columns (title and author). More columns are better. If columns could be customized, that will be great.

I am thinking this also. Hopefully we can see this in the next release.

**Comment by jasonzou** [comment]
Thanks. I am looking forward to the next release.

If possible, could you list what has been planned for future releases?
