### ISSUE TITLE
RIS导入后英文标题识别到中文翻译然后显示为中文

### ISSUE THREAD

**Issue by PandaNocturne** [ResearchHelper/research-helper#74]
### 问题描述

![image](https://github.com/ResearchHelper/research-helper/assets/84729049/2a44ecd0-66f2-4efd-8869-d3f0312f2bc3)
RIS的TT这个字段有标题翻译导入后标题全是中文
![image](https://github.com/ResearchHelper/research-helper/assets/84729049/c6157bf7-bb36-450a-aca1-68f38bf24700)

### 个人想法

1. 最好中英文是分开的，原文不变，因为原来的RIS最后可能会用上，比如导出统一格式(参考endnote或者zotero，endnote导出格式较好点)
2. 然后中英文希望可以设置个按钮来翻译，如下Zotero的翻译插件的示意

![image](https://github.com/ResearchHelper/research-helper/assets/84729049/31a46496-a68e-4e67-b0ca-91f638b3440f)

**Comment by HuntFeng** [comment]
This feature will be implemented in [Sophosia](https://sophosia.app/#/), please look forward to it!
